version: '3.8'

services:
  postgres:
    container_name: container_jpa_db
    image: postgres:alpine
    ports:
      - "5431:5432"
    restart: unless-stopped #always
    volumes:
      - jpa_db:/data/postgres
    networks:
      - jpa_db_net
#    environment:
#      POSTGRES_DB: ${PG_DATABASE}
#      POSTGRES_USER: ${PG_USER}
#      POSTGRES_PASSWORD: ${PG_PASSWORD}
#      PG_DATA: ${PG_DATA}
    env_file:
      - docker_db.env # contains data to setup postgres container db

volumes:
  jpa_db:

networks:
  jpa_db_net:
    driver: bridge